name: 'ReDOS Checker Action'
description: 'Check for ReDOS in a list of Regular Expressions'
author: 'CRS Project'

# Define your inputs here.
inputs:
  files:
    description: 'Files to check. Enter a glob pattern like "compiled/*".'
    required: true

# Define your outputs here.
outputs:
  vulnerable:
    description: 'A boolean indicating if the input was vulnerable'

runs:
  using: node20
  main: dist/index.js
